


#ifndef LCD_CFG_H_
#define LCD_CFG_H_



#include "../../mcal/dio/Dio_Cfg.h"



//LCD0

#define LCD0_D4_PIN_NUM	DioConf_LCD_D4_CHANNEL_ID_INDEX
#define LCD0_D5_PIN_NUM	DioConf_LCD_D5_CHANNEL_ID_INDEX
#define LCD0_D6_PIN_NUM	DioConf_LCD_D6_CHANNEL_ID_INDEX
#define LCD0_D7_PIN_NUM	DioConf_LCD_D7_CHANNEL_ID_INDEX


#define LCD0_EN_PIN_NUM	DioConf_LCD_E_CHANNEL_ID_INDEX
#define LCD0_RS_PIN_NUM	DioConf_LCD_RS_CHANNEL_ID_INDEX

//LCD1

#define LCD1_D4_PIN_NUM	DioConf_LCD1_D4_CHANNEL_ID_INDEX
#define LCD1_D5_PIN_NUM	DioConf_LCD1_D5_CHANNEL_ID_INDEX
#define LCD1_D6_PIN_NUM	DioConf_LCD1_D6_CHANNEL_ID_INDEX
#define LCD1_D7_PIN_NUM	DioConf_LCD1_D7_CHANNEL_ID_INDEX

#define LCD1_EN_PIN_NUM	DioConf_LCD1_E_CHANNEL_ID_INDEX
#define LCD1_RS_PIN_NUM	DioConf_LCD1_RS_CHANNEL_ID_INDEX




#endif /* LCD_CFG_H_ */