#include "LCD_Interface.h"
#include "LCD_Cfg.h"

LCD_ConfigChannel LCD_Configuration = {
  
  LCD0_RS_PIN_NUM, LCD0_EN_PIN_NUM, LCD0_D4_PIN_NUM, LCD0_D5_PIN_NUM, LCD0_D6_PIN_NUM, LCD0_D7_PIN_NUM,
  LCD1_RS_PIN_NUM, LCD1_EN_PIN_NUM, LCD1_D4_PIN_NUM, LCD1_D5_PIN_NUM, LCD1_D6_PIN_NUM, LCD1_D7_PIN_NUM

};